### PR TITLE
Validator.js version bump

### PR DESCRIPTION
**Pull request by IOAyman**
Many locals have been added.

[Changelog](https://github.com/chriso/validator.js/blob/master/CHANGELOG.md) | [Commit summery](https://github.com/chriso/validator.js/compare/5.4.0...5.6.0)

### CODE REVIEW

**Comment by timelf123** [comment]
5.7 is now out.

```
5.7.0

Added support for IPv6 in isURL() (#564)
Added support for urls without a host (e.g. file:///foo.txt) in isURL() (#563)
Added support for regular expressions in the isURL() host whitelist and blacklist (#562)
Added support for MasterCard 2-Series BIN (#576)
New locales (#575, #552)

5.6.0

Added an isMD5() validator (#557)
Fixed an exceptional case in isDate() (#566)
New locales (#559, #568, #571, #573)

5.5.0

Fixed a regex denial of service in trim() and rtrim() (#556)
Added an Algerian locale to isMobilePhone() (#540)
Fixed the Hungarian locale in isAlpha() and isAlphanumeric() (#541)
Added a Polish locale to isMobilePhone() (#545)
```

**Comment by IOAyman** [comment]
@timelf123 Yes, thank you!   I will push that bump.

**Comment by rustybailey** [comment]
This is now in v2.20.9. Thanks!

**Comment by IOAyman** [comment]
@rustybailey You're welcome :smile:

**Pull request merged**
