### PR TITLE
Improve IDE autocomplete for methods

### PR DESCRIPTION
**Pull request by AleksandrChernyavenko**
Add autocomplete to methods "checkQuery", "checkParams", "checkBody"  - http://joxi.ru/KAg7gPQi4njP1A

### CODE REVIEW

**Comment by gustavohenke** [comment]
Hi @AleksandrChernyavenko! Thanks for your contribution.
Could you please check the build log and fix what's wrong, so I can merge this in?

**Comment by AleksandrChernyavenko** [comment]
Thanks for answer!
I fixed build, so you can merge it.

**Comment by gustavohenke** [comment]
Do you mind squashing the commits?

Unfortunately, this repo is not configured to allow squashing or rebasing and I don't have permission to change :(

**Comment by AleksandrChernyavenko** [comment]
Thanks for accepting my pull request!

**Pull request closed without merging**
