### PR TITLE
Provide a default options value

### LINKED ISSUE #143: Inconstency between readme / doc and lib
doc says constructor `options` is optional but if we do not provide an object we got this error

```
TypeError: Cannot read property 'customValidators' of undefined
    at expressValidator (/.../node_modules/express-validator/lib/express_validator.js:101:20)
```

It is because this [call](https://github.com/ctavan/express-validator/blob/master/lib/express_validator.js#L72) does not provide a default `options` value. `_.defaults` will return null if `options` is null, even with a correct `defaults` object.

### PR DESCRIPTION
**Pull request by JSteunou**
should fix #143

### CODE REVIEW

**Comment by rustybailey** [comment]
Thanks, this was something that was lost during the refactor.

**Comment by rustybailey** [comment]
This fix has been published to npm as 2.12.1.

**Comment by JSteunou** [comment]
wow fast! thank you.

**Comment by rustybailey** [comment]
Ha ha. Just happened to sync up. I had just published the minor version you found a bug in.

**Pull request merged**
