### PR TITLE
Deleted 'isDate' from d.ts files.

### PR DESCRIPTION
**Pull request by sant123**

### CODE REVIEW

**Comment by gustavohenke** [comment]
Thanks!!

**Comment by sant123** [comment]
Glad to help @gustavohenke

**Comment by Algalord666** [comment]
how i can use a similar function to isDate()?

**Comment by gustavohenke** [comment]
Hi @Algalord666, you should use `isISO8601` instead. See https://www.npmjs.com/package/validator for docs

**Pull request merged**
