### PR TITLE
Allowed to use wildcards in schema validation

### PR DESCRIPTION
**Pull request by AndrasEszes**
Hy!

I need this feature in my projects, so I thought I will try to solve it. My problem was how to validate the "array-like" nested objects in a complex input, and maybe it's relevant to #125 issue. 

**Definition:**

``` js
req.checkBody({
 'users.*.email': {
    notEmpty: {
      errorMessage: 'Missing Email'
    },
    isEmail: {
      errorMessage: 'Invalid Email'
    }
  }
});
```

**Request:**

``` json
{
  "users": [
    {"email": "example@mail.com"},
    {"email": "example.mail.com"},
    {"notemail": "example2@mail.com"}
  ]
}
```

_or_

``` json
{
  "users": {
    "0": {"email": "example@mail.com"},
    "1": {"email": "example.mail.com"},
    "2": {"notemail": "example2@mail.com"}
  }
}
```

**Response:**

``` json
{
  "errors": [
    {
      "param": "users.1.email",
      "msg": "Invalid Email",
      "value": "example.mail.com"
    },
    {
      "param": "users.2.email",
      "msg": "Missing Email"
    },
    {
      "param": "users.2.email",
      "msg": "Invalid Email"
    }
  ]
}
```

### CODE REVIEW

**Comment by fyodorvi** [comment]
This is awesome!

**Comment by Zignd** [comment]
Amazing! I was looking for this exact same feature! It's a shame the repo owner have not even considered writing about it comment here.

**Comment by IOAyman** [comment]
Exactly what I was looking for. Glad you implemented that!
I was using _cutomValidators_ to do it.

**Comment by elwhizard** [comment]
This is really helpful. Please include this feature on the next release.

**Comment by rocketspacer** [comment]
Why this isn't in the documentation :D

**Comment by maZahaca** [comment]
Let's merge this! Pleeeeaaase!

**Comment by elTallarin** [comment]
Please merge this!!!

**Comment by s524797336** [comment]
Why this is still conflicting?

**Comment by gustavohenke** [comment]
Hello folks, [v4.0.0 has finally been released](https://github.com/ctavan/express-validator/releases/tag/v4.0.0), bringing with it the long awaited wildcard `*` support! 🎉 

Please check the README for complete docs, and also check the [upgrade guide](https://github.com/ctavan/express-validator/blob/v4.0.0/UPGRADE_GUIDE.md).

**Pull request closed without merging**
