### PR TITLE
REF #350 Fix for TypeScript Typings Revisted

### PR DESCRIPTION
**Pull request by taicho**
This has been a bad day. This is tested both in project tests and in
real project and should resolve the issues with imports in TypeScript.

Fixes: #350

### CODE REVIEW

**Comment by gustavohenke** [comment]
cc @IOAyman - do you mind reviewing?

**Comment by taicho** [comment]
@gustavohenke My pleasure! I was driven by my desire to use this great library. :) The problem for TypeScript users like myself was that if using the recommended "import" syntax to try and reference/require the library it would result in compile-time errors preventing compilation altogether. The only alternatives were to either delete the definitions entirely so TS was essentially blind to the library or use "require"; both of these options resulted in TS being unaware of the typings rendering them useless. As you can see from my multiple attempts yesterday I am not the most competent typings author not to mention I wasn't testing properly and was a little impatient. That being said this should completely resolve this issue for TS users who want to use your library. On a side note, I'm uncertain if this broke due to recent updates to TS, what I am certain about is that without this fix the library was unusable in the current version (2.3.4) of TS.

**Comment by emauricio** [comment]
Hi there, quick question about in this version how to declare the custom validators?
in the prev. version i was able to do like 
```
declare global {
    namespace ExpressValidator {      
        interface Validator {
           //here the custom stuff
...
```
but now is not working, any suggestions, already try to google it, but no much about this topic, thx in advance.

versions
 - typescript: 2.4.1 
 - express-validator: 3.2.1

**Comment by nicolashenry** [comment]
I use this in a .d.ts file: 
```typescript
import 'express-validator';
declare module 'express-validator' {
	interface Validator {
		//here the custom stuff
	}
}
```

**Comment by gustavohenke** [comment]
Thanks for the help, @nicolashenry!
I just added a test for this: a8dde3138b5edabfe12c318404f14c1d78205e32

**Comment by emauricio** [comment]
Ohh thank you very much 😄

**Pull request merged**
